#!/bin/bash
replications=3

array=( $(seq 1 0.5 13 ) )
name_arr=("Tahoe" "Reno")
B=1460
echo "-------------Tahoe----------------"
echo "CBR      Throughput                 Packet Drop Rate"

len=${#array[@]}
for name in ${name_arr[@]}; do 
    echo $name
    echo $B
    idx=0
    for i in ${array[@]}; do
        fileName="./output/"
        fileName+="$name"
        fileName+="/result"
        fileName+="$idx"
        fileName+=".csv"
        ((idx++))
        echo "thput,droprate,cal5,cal6" > $fileName
        for j in $(seq 1 $replications); do
        # printf $fileNamer    
            ns exp1.tcl $name $i $B
            printf $i
            ./pyth $fileName $B
        done
    done
    ./plotfig $name $len $B
done 


# echo "==========================================================================================="
# echo "------------------Reno-------------------"
# echo "CBR      Throughput                  Packet Drop Rate"

# for i in ${array[@]}
# do
# ns exp1.tcl Reno $i 1460
# printf $i 
# ./pyth
# done

# echo "packetSize = 512"

# echo "-------------Tahoe----------------"
# echo "CBR      Throughput                 Packet Drop Rate"

# array=( $(seq 8 0.5 18 ) )
# for i in ${array[@]}
# do
# ns exp1.tcl Tahoe $i 512
# printf $i 
# ./pyth
# done

# echo "==========================================================================================="
# echo "------------------Reno-------------------"
# echo "CBR      Throughput                  Packet Drop Rate"

# for i in ${array[@]}
# do
# ns exp1.tcl Reno $i 512
# printf $i 
# ./pyth
# done

