#!/bin/bash
replications=10

array=( $(seq 1 1 45 ) )
name_arr=("Tahoe" "Reno")
B=1460
rtt_arr=(0 0.03 0.09)
# rtt=0
len=${#array[@]}
for name in ${name_arr[@]}; do 
    echo $name
    echo $B
    idx_rtt=0
    for k in ${rtt_arr[@]}; do 
        idx=0
        for i in ${array[@]}; do
            fileName="./output/"
            fileName+="$name"
            fileName+="/rtt"
            fileName+="$idx_rtt"
            fileName+="/result"
            fileName+="$idx"
            fileName+=".csv"
            ((idx++))
            echo "thput,droprate,cal5,cal6" > $fileName
            for j in $(seq 1 $replications); do
            # printf $fileNamer    
                ns exp3.tcl $name $i $B $k
                printf $i
                ./pyth $fileName $i $B
            done
        done
        ./plotfig $name $len $B $idx_rtt
        ((idx_rtt++)) 
    done 
done 


B=512


for name in ${name_arr[@]}; do 
    echo $name
    echo $B
    idx_rtt=0
    for k in ${rtt_arr[@]}; do 
        idx=0
        for i in ${array[@]}; do
            fileName="./output/"
            fileName+="$name"
            fileName+="/rtt"
            fileName+="$idx_rtt"
            fileName+="/result"
            fileName+="$idx"
            fileName+=".csv"
            ((idx++))
            echo "thput,droprate,cal5,cal6" > $fileName
            for j in $(seq 1 $replications); do
            # printf $fileNamer    
                ns exp3.tcl $name $i $B $k
                printf $i
                ./pyth $fileName $i $B
            done
        done
        ./plotfig $name $len $B $idx_rtt
        ((idx_rtt++)) 
    done 
done 